name: Fetch wireproxy latest version to GitLab

on:
  workflow_dispatch:
  schedule:
    - cron: "30 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setting GitLab repository
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
          git config --global user.email "misakablog@protonmail.com"
          git config --global user.name "misakablog"
          git clone git@gitlab.com:misakablog/warp-script.git
      - name: Check and fetch wireproxy latest version
        run: |
          cd warp-script
          rm -f files/wireproxy/wireproxy-amd64 files/wireproxy/wireproxy-arm64 files/wireproxy/wireproxy-s390x files/wireproxy/wireproxy-fetchlog.txt
          actions_date=$(date)
          repo_last_ver=$(curl -Ls "https://api.github.com/repos/octeep/wireproxy/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          wget -N https://github.com/octeep/wireproxy/releases/download/$repo_last_ver/wireproxy_linux_amd64.tar.gz
          tar -zxvf wireproxy_linux_amd64.tar.gz
          rm -f wireproxy_linux_amd64.tar.gz
          mv -f wireproxy files/wireproxy/wireproxy-amd64
          wget -N https://github.com/octeep/wireproxy/releases/download/$repo_last_ver/wireproxy_linux_arm64.tar.gz
          tar -zxvf wireproxy_linux_arm64.tar.gz
          rm -f wireproxy_linux_arm64.tar.gz
          mv -f wireproxy files/wireproxy/wireproxy-arm64
          wget -N https://github.com/octeep/wireproxy/releases/download/$repo_last_ver/wireproxy_linux_s390x.tar.gz
          tar -zxvf wireproxy_linux_s390x.tar.gz
          rm -f wireproxy_linux_s390x.tar.gz
          mv -f wireproxy files/wireproxy/wireproxy-s390x
          cat <<EOF > files/wireproxy/wireproxy-fetchlog.txt
          # wireproxy fetch log generated by GitHub Actions
          Last Version: $repo_last_ver
          Fetch Date: $actions_date
          EOF
      - name: Upload to GitLab
        run: |
          cd warp-script
          git add .
          git commit -m "Uploaded by Github Actions, Date: $(date)"
          git push
