name: Fetch warp-go latest version to GitLab

on:
  workflow_dispatch:
  schedule:
    - cron: "30 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setting GitLab repository
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
          git config --global user.email "misakablog@protonmail.com"
          git config --global user.name "misakablog"
          git clone git@gitlab.com:misakablog/warp-script.git
      - name: Check and fetch warp-go latest version
        run: |
          rm -f warp-script/files/warp-go/warp-go-amd64 warp-script/files/warp-go/warp-go-amd64v2 warp-script/files/warp-go/warp-go-amd64v3 warp-script/files/warp-go/warp-go-amd64v4 warp-script/files/warp-go/warp-go-arm64 warp-script/files/warp-go/warp-go-s390x warp-script/files/warp-go/warpgo-fetchlog.txt
          actions_date=$(date)
          repo_last_ver=$(curl -Ls "https://gitlab.com/api/v4/projects/ProjectWARP%2Fwarp-go/releases" | grep -oP '"tag_name":"v\K[^\"]+' | head -n 1)
          wget -N https://gitlab.com/ProjectWARP/warp-go/-/releases/v"$repo_last_ver"/downloads/warp-go_"$repo_last_ver"_linux_amd64.tar.gz
          tar -zxvf warp-go_"$repo_last_ver"_linux_amd64.tar.gz
          rm -f warp-go_"$repo_last_ver"_linux_amd64.tar.gz LICENCE README.md README.zh_CN.md
          mv -f warp-go warp-script/files/warp-go/warp-go-amd64
          wget -N https://gitlab.com/ProjectWARP/warp-go/-/releases/v"$repo_last_ver"/downloads/warp-go_"$repo_last_ver"_linux_amd64v2.tar.gz
          tar -zxvf warp-go_"$repo_last_ver"_linux_amd64v2.tar.gz
          rm -f warp-go_"$repo_last_ver"_linux_amd64v2.tar.gz LICENCE README.md README.zh_CN.md
          mv -f warp-go warp-script/files/warp-go/warp-go-amd64v2
          wget -N https://gitlab.com/ProjectWARP/warp-go/-/releases/v"$repo_last_ver"/downloads/warp-go_"$repo_last_ver"_linux_amd64v3.tar.gz
          tar -zxvf warp-go_"$repo_last_ver"_linux_amd64v3.tar.gz
          rm -f warp-go_"$repo_last_ver"_linux_amd64v3.tar.gz LICENCE README.md README.zh_CN.md
          mv -f warp-go warp-script/files/warp-go/warp-go-amd64v3
          wget -N https://gitlab.com/ProjectWARP/warp-go/-/releases/v"$repo_last_ver"/downloads/warp-go_"$repo_last_ver"_linux_amd64v4.tar.gz
          tar -zxvf warp-go_"$repo_last_ver"_linux_amd64v4.tar.gz
          rm -f warp-go_"$repo_last_ver"_linux_amd64v4.tar.gz LICENCE README.md README.zh_CN.md
          mv -f warp-go warp-script/files/warp-go/warp-go-amd64v4
          wget -N https://gitlab.com/ProjectWARP/warp-go/-/releases/v"$repo_last_ver"/downloads/warp-go_"$repo_last_ver"_linux_arm64.tar.gz
          tar -zxvf warp-go_"$repo_last_ver"_linux_arm64.tar.gz
          rm -f warp-go_"$repo_last_ver"_linux_arm64.tar.gz LICENCE README.md README.zh_CN.md
          mv -f warp-go warp-script/files/warp-go/warp-go-arm64
          wget -N https://gitlab.com/ProjectWARP/warp-go/-/releases/v"$repo_last_ver"/downloads/warp-go_"$repo_last_ver"_linux_s390x.tar.gz
          tar -zxvf warp-go_"$repo_last_ver"_linux_s390x.tar.gz
          rm -f warp-go_"$repo_last_ver"_linux_s390x.tar.gz LICENCE README.md README.zh_CN.md
          mv -f warp-go warp-script/files/warp-go/warp-go-s390x
          cat <<EOF > warp-script/files/warp-go/warpgo-fetchlog.txt
          # warp-go fetch log generated by GitHub Actions
          Last Version: $repo_last_ver
          Fetch Date: $actions_date
          EOF
      - name: Upload to GitLab
        run: |
          cd warp-script
          git add .
          git commit -m "Uploaded by Github Actions, Date: $(date)"
          git push
